---
- name: Create 'test' user
  hosts: all_targets
  become: true
  tasks:
  - name: Create User
    user: 
      name: test 
      password: changeit2020 
      groups: ansible 
      shell: /bin/bash