---
# tasks file for roles/custom-maven
- name: Install Maven
  hosts: all_targets
  become: true
  vars:
    MAVEN_DOWNLOAD_URL: "http://www.apache.org/dist/maven/maven-{{ maven_major }}/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
  tasks:
  
    - name: Check If Maven is already installed
      shell: "mvn -version | grep -w 'Apache Maven' | awk '{print $3}'"
      register: maven_version_installed
  
    - name: Print Maven Version Installed
      debug: "msg={{ maven_version_installed.stdout }}"
    
    # No install
    - block:
    
      - name: Download and Unarchive maven
        unarchive:
          src: "{{ MAVEN_DOWNLOAD_URL }}"
          dest: "{{maven_home}}"
          copy: no

      - name: Create maven symlink to /usr/bin
        file:
          src: "{{ maven_home }}/apache-maven-{{ maven_version }}/bin/mvn"
          dest: /usr/bin/mvn
          state: link

      - name: Configure maven and its environment variables
        lineinfile:
          dest: "{{maven_env_file}}"
          line: "{{ item.line }}"
          create: yes
          state: present
        with_items:
        - { line: 'M2_HOME={{maven_home}}/apache-maven-{{maven_version}}' }
        - { line: 'PATH=$PATH:$M2_HOME/bin' }

      - name: Exports/Run maven env file for make M2_HOME available globally
        shell: "source {{maven_env_file}}"
      
      when: maven_version_installed.stdout == ""