---
- name: Create Directory 'example'
  hosts: all_targets
  become: true
  tasks:
  - name: Create Directory
    file:
        path: "/home/ansible/example"
        state: directory
        mode: 755
        owner: ansible
        group: ansible