---
- name: Install Package httpd
  hosts: all_targets
  become: true
  tasks:
  - name: Install Package httpd
    yum: name=httpd state=present
  - name: Start httpd service
    service: name=httpd state=started