---

# Prepare Environment for MariaDB
- name: Prepare Environment for MariaDB
  hosts: db_servers
  become: yes
  tasks:

    - name: Install common dependencies
      yum:
        name:
          - libselinux-python
          - libsemanage-python
          - firewalld
        state: installed

    - name: Start firewalld Service
      service: name=firewalld state=started enabled=yes


# Install & Configure MariaDB
- name: Install & Configure mariadb
  hosts: db_servers
  become: true
  vars:
    mysql_port: 3306
  tasks:

    - name: Install mariadb Package
      yum:
        name:
          - mariadb-server
          - MySQL-python
        state: installed

    - name: Create Custom mariadb Configuration file
      copy: src=files/my.cnf dest=/etc/my.cnf

    - name: Start mariadb Service
      service: name=mariadb state=started enabled=yes

    - name: Insert firewalld Rule for mariadb 
      firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled


# Prepare Database for MariaDB
- name: Prepare Database for MariaDB
  hosts: db_servers
  become: true
  tasks:

    - name: Create "{{ db_name }}" Database
      mysql_db: name={{ db_name }} state=present

    - name: Create "{{ db_user }}" DB User
      mysql_user: name={{ db_user }} password={{ db_password }} priv=*.*:ALL host='172.20.1.100' state=present

    - name: Move db-load-script to db host
      copy:
        src: files/db-load-script.sql
        dest: /tmp/db-load-script.sql

    - name: Load Inventory Data
      shell: mysql -f < /tmp/db-load-script.sql