---

- name: Prepare Environment for Apache
  hosts: web_servers
  become: yes
  tasks:

    - name: Install common dependencies
      yum:
        name:
          - httpd
          - firewalld
        state: installed

- name: Install / Configure Apache
  hosts: web_servers
  become: true
  vars:
    apache_configuration_port: 8090
  tasks:

    - name: Start/Enable Services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - httpd
        - firewalld

    - name: Change Apache Configuration Port -> replace port 80 to 8090
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: "Listen 80"
        replace: "Listen {{ apache_configuration_port }}"

    - name: Restart Apache Service
      # - service: name=httpd state=restarted
      service:
        name: httpd
        state: restarted

    - name: Add firewall Rule for Apache
      firewalld:
        port: "{{ apache_configuration_port }}/tcp"
        zone: public
        permanent: yes
        state: enabled
        immediate: yes

- name: Prepare index.html
  hosts: web_servers
  become: true
  tasks:

    - lineinfile:
      path: /var/www/html/index.html
      line: 'This line was added using Ansible lineinfile module!'
      create: yes