---
- name: Install JRE
  hosts: all_targets
  become: true
  vars:
    JRE_VERSION: java-1.8.0-openjdk
  tasks:
  - name: Install OpenJDK Java JRE
    yum:
      name: "{{ JRE_VERSION }}"
      state: present