---
- name: Install & Start httpd Package
  hosts: all_targets
  any_errors_fatal: true
  tasks:

  - name: Install httpd Package
    yum: name=httpd state=present
    
  - name: Start httpd service
    service: name=httpd state=started