---
- name: Install Common Dependencies
  hosts: all_targets
  become: true
  tasks:

  - name: Install Common Dependencies
    yum: 
      name: 
        - libselinux-python
        - libsemanage-python
        - firewalld
      state: latest