---
- hosts: all
  gather_facts: yes
  tasks:

    - setup: filter='ansible_dist*'
      register: facts

    - debug: var=facts.ansible_facts.ansible_distribution
    
    - shell: echo "{{facts.ansible_facts.ansible_distribution}}" > /tmp/output.txt